module.exports = {  
  'PORT': process.env.REACT_APP_PORT || 3000,
  'ACCOUNTS_API': process.env.REACT_APP_ACCOUNTS_API,
  'WORDS_API': process.env.REACT_APP_WORDS_API,
  'AWS_IDENTITY_POOL_ID': process.env.REACT_APP_AWS_IDENTITY_POOL_ID,
  'FIREBASE_API_KEY': process.env.REACT_APP_FIREBASE_API_KEY,
  'FIREBASE_AUTH_DOMAIN': process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  'FIREBASE_DATABASE_URL': process.env.REACT_APP_FIREBASE_DATABASE_URL,
  'FIREBASE_STORAGE_BUCKET': process.env.REACT_APP_FIREBASE_STORAGE_BUCKET
}
